# https://taskfile.dev

version: "3"

tasks:
  default:
    silent: true
    cmds:
      - cmd: task --list-all

  clean:
    cmds:
      - cmd: rm -rf build
        platforms: [linux]

  config_linux:
    internal: true
    platforms: [linux]
    cmds:
      - conan install . --build=missing -s build_type=Release --profile:build=profiles/gcc13_x64 --profile:host=profiles/gcc13_x64
      - cmake --preset conan-release
    sources:
      - CMakePresets.json
      - conanfile.*
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - include/**/CMakeLists.txt
      - tests/**/CMakeLists.txt
      - external/**/CMakeLists.txt
      - cmake/**/CMakeLists.txt
    generates:
      - build/Release/compile_commands.json
      - build/compile_commands.json

  config_linux_debug:
    internal: true
    platforms: [linux]
    cmds:
      - conan install . --build=missing -s build_type=Debug --profile:build=profiles/gcc13_x64 --profile:host=profiles/gcc13_x64
      - cmake --preset conan-debug
    sources:
      - CMakePresets.json
      - conanfile.*
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - include/**/CMakeLists.txt
      - tests/**/CMakeLists.txt
      - external/**/CMakeLists.txt
      - cmake/**/CMakeLists.txt
    generates:
      - build/Debug/compile_commands.json
      - build/compile_commands.json

  config:
    cmds:
      - task: config_linux

  config_debug:
    cmds:
      - task: config_linux_debug

  build:
    cmds:
      - task: config
      - cmd: cmake --build build/Release

  build_debug:
    cmds:
      - task: config_debug
      - cmd: cmake --build build/Debug

  run:
    cmds:
      - task: build
      - cmd: build/Release/src/popup "test message"

  run_debug:
    cmds:
      - task: build_debug
      - cmd: build/Debug/src/popup "test message"

  install:
    cmds:
      - task: build
      - cmake --install build/Release --prefix install

  nix_install:
    cmds:
      - cmake -S . -B build/Release -DCMAKE_BUILD_TYPE=Release
      - cmake --build build/Release
      - cmake --install build/Release --prefix install
